name: Deploy Backend

on:
  push:
    branches:
      - main  # Change to your deployment branch
  pull_request:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Debug Workspace
        run: ls -R  # ✅ List all files to verify the Dockerfile location

      - name: Build and Push Backend Docker Image
        run: |
          docker buildx build \
            --file docker/Dockerfile.backend \ 
            --iidfile /tmp/docker-actions-toolkit-Euaah9/iidfile \
            --tag 100xdevs/todo-app-backend:${{ github.sha }} \
            --metadata-file /tmp/docker-actions-toolkit-Euaah9/metadata-file \
            --push .
